/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USER;


import CONFIG.config;  // Import sa imong config class
import CONFIG.Session; // Import sa imong Session class
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;    // Para sa Connection ug PreparedStatement
import java.text.SimpleDateFormat; // Para sa JSpinner date
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Jingkie
 */
public class bookaservice extends javax.swing.JFrame {

    public int selectedServiceId;
    public int selectedProviderId;
    public double servicePrice;
    
    public bookaservice() {
        initComponents();
        
         Color navy = new Color(35, 66, 106);
        
        applyAdminButtonStyle(jButton2, navy);   
        

        
        // Pag-set sa Spinner ngadto sa Date model
java.util.Calendar calendar = java.util.Calendar.getInstance();
java.util.Date initDate = calendar.getTime();
javax.swing.SpinnerDateModel dateModel = new javax.swing.SpinnerDateModel(initDate, null, null, java.util.Calendar.DAY_OF_YEAR);
jSpinner1.setModel(dateModel);

// I-format ang itsura sa Spinner (Month/Day/Year Hour:Minute AM/PM)
javax.swing.JSpinner.DateEditor editor = new javax.swing.JSpinner.DateEditor(jSpinner1, "MM/dd/yyyy hh:mm a");
jSpinner1.setEditor(editor);
    }

    
    // I-delete ang karaan nga public bookaservice()
    // Kani nga mga methods maoy "pultahan" para sa Dashboard
// Gamita kini nga version sa bookaservice.java
// I-update ni nga method sa bookaservice.java
public void setBookingDetails(String sname, String pname, String price, int sid, int pid) {
    this.lbl_serviceName.setText("Selected Service: " + sname);
    this.lbl_providerName.setText("Provider Name: " + pname); // show actual provider name
    this.lbl_totalPrice.setText("₱" + price);
    this.jLabel7.setText("Status: Pending"); // default status
    this.selectedServiceId = sid;
    this.selectedProviderId = pid;

    try {
        this.servicePrice = Double.parseDouble(price.replace("₱", "").replace(",", "").trim());
    } catch (Exception e) {
        this.servicePrice = 0.0;
    }
}


private void applyAdminButtonStyle(JButton btn, Color baseColor) {
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(false);
        btn.setOpaque(true);
        btn.setBackground(baseColor);
        btn.setForeground(Color.WHITE);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 0));

        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {
                btn.setBackground(baseColor.brighter());
                btn.setBorder(BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE));
            }
            @Override
            public void mouseExited(MouseEvent evt) {
                btn.setBackground(baseColor);
                btn.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 0));
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_serviceName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_providerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_totalPrice = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 66, 106));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Blue White Modern Minimalist Interior Designer Personal Branding Logo(1)(1).jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 179, 96));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back to Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 31, 280, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 66, 106));
        jLabel1.setText("Book a Service");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 270, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Service Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 140, 50));

        lbl_serviceName.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbl_serviceName.setForeground(new java.awt.Color(35, 66, 106));
        lbl_serviceName.setText("Selected Service: ");
        jPanel1.add(lbl_serviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 540, 80));

        jPanel3.setBackground(new java.awt.Color(35, 66, 106));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Provider Information");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 236, 37));

        lbl_providerName.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbl_providerName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_providerName.setText("Provider Name:");
        jPanel3.add(lbl_providerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 340, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 540, 120));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 360, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 66, 106));
        jLabel8.setText("Schedule Date & Time: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 220, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 66, 106));
        jLabel9.setText("Service Address: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, 40));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 360, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setText("Payment Summary");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 200, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel11.setText("Full Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 180, 20));

        lbl_totalPrice.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_totalPrice.setForeground(new java.awt.Color(35, 66, 106));
        lbl_totalPrice.setText("Total Amount:");
        jPanel1.add(lbl_totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 450, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Booking Inputs");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 30));

        jButton1.setBackground(new java.awt.Color(35, 66, 106));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONFIRM BOOKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 410, 60));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 322, 360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String address = txt_address.getText().trim();
    
    if (address.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please fill in the Address!");
        return;
    }

    // Format the date from Spinner
    java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String bookingDate = format.format(jSpinner1.getValue());

    String sql = "INSERT INTO tbl_bookings (u_id, s_id, p_id, b_date, b_address, b_total, b_status) "
               + "VALUES (?, ?, ?, ?, ?, ?, 'Pending')";

    config conf = new config();
    try (Connection conn = conf.connectDB();
         PreparedStatement pst = conn.prepareStatement(sql)) {
        
        // Siguraduhon nga naay sulod ang Session
        int currentUserId = Session.getUserId();
        if (currentUserId == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Session Expired. Please Login again.");
            return;
        }

        pst.setInt(1, currentUserId);    
        pst.setInt(2, selectedServiceId);      
        pst.setInt(3, selectedProviderId);     
        pst.setString(4, bookingDate);       
        pst.setString(5, address);
        pst.setDouble(6, servicePrice);

        int result = pst.executeUpdate();
        
        if (result > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Booking Submitted Successfully!");
          
        }

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         udashboard dash = new udashboard();
    dash.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookaservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookaservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookaservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookaservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookaservice().setVisible(true);
            }
        });
    }
    
    // Kini nga method maoy dawat sa data gikan sa Dashboard
// Kinahanglan 5 ka parameters ang naa diri: String, String, int, int, double
public void setDetails(String sname, String sprice_str, int sid, int pid, double sprice) {
    this.lbl_serviceName.setText(sname);
    this.lbl_totalPrice.setText(sprice_str);
    this.selectedServiceId = sid;
    this.selectedProviderId = pid;
    this.servicePrice = sprice;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl_providerName;
    private javax.swing.JLabel lbl_serviceName;
    private javax.swing.JLabel lbl_totalPrice;
    private javax.swing.JTextField txt_address;
    // End of variables declaration//GEN-END:variables
}
