
package ADMIN;

import CONFIG.config;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class ServiceManagement extends javax.swing.JFrame {

   config cfg = new config();
   boolean isEditMode = false;

    public ServiceManagement() {
        initComponents();
        tableStyle();
        loadServices();
        cfg.sessionGuard(this);
        
        java.awt.Color navy = new java.awt.Color(35, 66, 106);

    // Apply Styles to Sidebar/Navigation
    styleAdminButtons(jButton3, navy); // Back to Home

    // Apply Styles to Action Buttons
    styleAdminButtons(Add, navy);
    styleAdminButtons(EDIT, navy);
    styleAdminButtons(delete, navy);
    styleAdminButtons(jButton2, navy); // Search Button
    
    // Modern Search Field Border
    jTextFieldSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
        javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    }

 // ================= LOAD SERVICES =================
public void loadServices() {
    try {
        String sql;
        // Check if current user is a provider
        if (CONFIG.Session.getRole().equalsIgnoreCase("PROVIDER")) {
            // Only load services for the logged-in provider
            sql = "SELECT * FROM tbl_services WHERE provider_id = " + CONFIG.Session.getUserId();
        } else {
            // Admin sees all services
            sql = "SELECT * FROM tbl_services";
        }
        cfg.displayData(sql, jTable1);
    } catch (Exception e) {
        System.out.println("CRITICAL ERROR: " + e.getMessage());
    }
}

   
private void searchService() {
    String query = jTextFieldSearch.getText().trim();
    String sql;

    if (CONFIG.Session.getRole().equalsIgnoreCase("PROVIDER")) {
        // Provider search only within their own services
        sql = "SELECT * FROM tbl_services WHERE provider_id = " + CONFIG.Session.getUserId()
            + " AND (s_name LIKE '%" + query + "%' OR s_category LIKE '%" + query + "%')";
    } else {
        // Admin can search all services
        sql = "SELECT * FROM tbl_services WHERE s_name LIKE '%" + query + "%' OR s_category LIKE '%" + query + "%'";
    }

    cfg.displayData(sql, jTable1);
}

private void styleAdminButtons(javax.swing.JButton btn, java.awt.Color baseColor) {
    btn.setBorderPainted(false);
    btn.setFocusPainted(false);
    btn.setContentAreaFilled(false); 
    btn.setOpaque(true); 
    btn.setBackground(baseColor);
    btn.setForeground(java.awt.Color.WHITE);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btn.setFont(new java.awt.Font("Segoe UI Bold", java.awt.Font.PLAIN, 13));
    
    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btn.setBackground(baseColor.brighter()); 
        }
        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btn.setBackground(baseColor);
        }
    });
}

private void tableStyle() {
    jTable1.setRowHeight(30);
    jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12));
    jTable1.setGridColor(new java.awt.Color(230, 230, 230));
    jTable1.setSelectionBackground(new java.awt.Color(35, 66, 106));
    jTable1.setSelectionForeground(java.awt.Color.WHITE);

    jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI Black", 0, 13));
    jTable1.getTableHeader().setBackground(new java.awt.Color(35, 66, 106));
    jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);
    jTable1.getTableHeader().setOpaque(false);
    
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 66, 106));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Blue White Modern Minimalist Interior Designer Personal Branding Logo(1)(1).jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 74));

        jButton3.setBackground(new java.awt.Color(35, 66, 106));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back to Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, 27));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 590));

        jPanel3.setBackground(new java.awt.Color(35, 66, 106));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVICES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 548, 76));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 548, 352));

        Add.setBackground(new java.awt.Color(35, 66, 106));
        Add.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 90, 40));

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 94, 40));

        jButton2.setBackground(new java.awt.Color(35, 66, 106));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 100, 40));

        EDIT.setBackground(new java.awt.Color(35, 66, 106));
        EDIT.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        EDIT.setForeground(new java.awt.Color(255, 255, 255));
        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });
        jPanel1.add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 90, 40));

        delete.setBackground(new java.awt.Color(35, 66, 106));
        delete.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
       searchService();
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     searchService();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       admindashboard ad = new admindashboard();
    ad.setVisible(true);
    ad.setLocationRelativeTo(null);
    this.dispose(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int rowIndex = jTable1.getSelectedRow();
    
    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select an item!");
    } else {
        // Only open EditService if the EDIT button was clicked first
        if (isEditMode) {
            TableModel model = jTable1.getModel();
            EditService es = new EditService();

            // Pushing data from table to EditService fields
            es.jTextField1.setText(model.getValueAt(rowIndex, 0).toString()); // ID
            es.jTextField2.setText(model.getValueAt(rowIndex, 1).toString()); // Name
            es.jTextField3.setText(model.getValueAt(rowIndex, 3).toString()); // Price
            es.jComboBox1.setSelectedItem(model.getValueAt(rowIndex, 2).toString()); // Category
            es.jTextField4.setText(model.getValueAt(rowIndex, 4).toString()); // Status

            // Lock the ID field so it can't be changed
            es.jTextField1.setEditable(false);

            es.setVisible(true);
            es.setLocationRelativeTo(null);
            this.dispose(); // Close management screen
            
            isEditMode = false; // Reset mode for next time
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // 1. Create an instance of the AddService form
    AddService as = new AddService();
    
    // 2. Make the AddService form appear
    as.setVisible(true);
    
    // 3. Center it on the screen (optional but looks professional)
    as.setLocationRelativeTo(null);
    
    // 4. Close the current ServiceManagement window
    this.dispose();
    }//GEN-LAST:event_AddActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        isEditMode = true; 
    JOptionPane.showMessageDialog(this, "Click a Service in the table to edit its details.");
    }//GEN-LAST:event_EDITActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      int rowIndex = jTable1.getSelectedRow();

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(this, "Please select a service to delete!");
    } else {
        // Kuhaon ang ID gikan sa Table Model
        javax.swing.table.TableModel model = jTable1.getModel();
        String serviceId = model.getValueAt(rowIndex, 0).toString();
        String serviceName = model.getValueAt(rowIndex, 1).toString();

        // Confirmation Message para sigurado gyud ang user
        int confirm = JOptionPane.showConfirmDialog(null, 
            "Are you sure you want to delete service: " + serviceName + "?", 
            "Delete Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // SQL query para i-delete ang service
                // Siguroha nga 's_id' ang ngalan sa column sa imong database
                String sql = "DELETE FROM tbl_services WHERE s_id = '" + serviceId + "'";
                
                // Tawgon ang updateData (bisag void ni, mo-execute gihapon ang SQL)
                cfg.updateData(sql); 

                // Pahibalo nga deleted na
                JOptionPane.showMessageDialog(this, "Service successfully deleted!");
                
                // I-load balik ang table para mawala ang gi-delete
                loadServices(); 
                
            } catch (Exception e) {
                System.out.println("Delete Error: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Error deleting service: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ServiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ServiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ServiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ServiceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            if (CONFIG.Session.getUserId() == 0) { // <-- Use getter instead of direct access
                javax.swing.JOptionPane.showMessageDialog(null, "Please Login First!");
                new MAIN.login().setVisible(true);
            } else {
                new ServiceManagement().setVisible(true);
            }
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
